//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.PriceMaterials = new HashSet<PriceMaterials>();
            this.RachetStoimosti = new HashSet<RachetStoimosti>();
            this.Specifikaciya = new HashSet<Specifikaciya>();
        }
    
        public int Id_Mat { get; set; }
        public string Name { get; set; }
        public string Kod { get; set; }
        public string Kolichestvo { get; set; }
        public Nullable<int> Id_EdIzm { get; set; }
    
        public virtual EdinicaIzmereniya EdinicaIzmereniya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceMaterials> PriceMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RachetStoimosti> RachetStoimosti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specifikaciya> Specifikaciya { get; set; }
    }
}
