//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.Class
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BurgerPlusEntities : DbContext
    {
        public BurgerPlusEntities()
            : base("name=BurgerPlusEntities")
        {
        }

        private static BurgerPlusEntities _context;
        public static BurgerPlusEntities GetContext()
        {
            if (_context == null)
                _context = new BurgerPlusEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EdinicaIzmereniya> EdinicaIzmereniya { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<PriceMaterials> PriceMaterials { get; set; }
        public virtual DbSet<PriceProdukciya> PriceProdukciya { get; set; }
        public virtual DbSet<Produkciya> Produkciya { get; set; }
        public virtual DbSet<RachetStoimosti> RachetStoimosti { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Specifikaciya> Specifikaciya { get; set; }
        public virtual DbSet<Stoimost> Stoimost { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Zakazchiki> Zakazchiki { get; set; }
        public virtual DbSet<ZakazPokupatelya> ZakazPokupatelya { get; set; }
    }
}
