//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceMaterials
    {
        public int Id_PriceMat { get; set; }
        public int Id_Mat { get; set; }
        public string Price { get; set; }
    
        public virtual Materials Materials { get; set; }
    }
}
