//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceProdukciya
    {
        public int Id_PriceProd { get; set; }
        public int Id_Prod { get; set; }
        public string Price { get; set; }
    
        public virtual Produkciya Produkciya { get; set; }
    }
}
