//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class RachetStoimosti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RachetStoimosti()
        {
            this.Stoimost = new HashSet<Stoimost>();
        }
    
        public int Id_Rachet { get; set; }
        public Nullable<int> Id_Prod { get; set; }
        public Nullable<int> Id_Mat { get; set; }
        public int Id_EdIzm { get; set; }
        public string Kolichestvo { get; set; }
        public string Price { get; set; }
    
        public virtual EdinicaIzmereniya EdinicaIzmereniya { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Produkciya Produkciya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stoimost> Stoimost { get; set; }
    }
}
