//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifikaciya
    {
        public int Id_Specif { get; set; }
        public int Id_Mat { get; set; }
        public int Id_EdIzm { get; set; }
        public string Kolichestvo { get; set; }
    
        public virtual EdinicaIzmereniya EdinicaIzmereniya { get; set; }
        public virtual Materials Materials { get; set; }
    }
}
