//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stoimost
    {
        public int Id_Stoimost { get; set; }
        public int Id_Rachet { get; set; }
        public string Itogo { get; set; }
    
        public virtual RachetStoimosti RachetStoimosti { get; set; }
    }
}
