//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakazPokupatelya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZakazPokupatelya()
        {
            this.Zakazchiki = new HashSet<Zakazchiki>();
        }
    
        public int Id_Zakaz { get; set; }
        public int Id_Prod { get; set; }
        public string Kolichestvo { get; set; }
        public int Id_EdIzm { get; set; }
        public string Price { get; set; }
        public string Summa { get; set; }
    
        public virtual EdinicaIzmereniya EdinicaIzmereniya { get; set; }
        public virtual Produkciya Produkciya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazchiki> Zakazchiki { get; set; }
    }
}
