//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazchiki
    {
        public int Id_Zakazchika { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Inn { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public bool Salesman { get; set; }
        public bool Buyer { get; set; }
        public int Id_Zakaz { get; set; }
        public int Id_User { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ZakazPokupatelya ZakazPokupatelya { get; set; }
    }
}
